apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi

spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: moulali12/flaskapi:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_RUN_PORT
              value: "5000"
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: root
            - name: DB_NAME
              value: user_db